version: '3'
services:
  doc:
    image: redocly/redoc
    volumes:
      - ./api:/usr/share/nginx/html/api
    environment:
      SPEC_URL: api/swagger.yml
    ports:
      - 8080:80
  mock:
    image: stoplight/prism
    volumes:
      - ./api:/api
    command: >
      mock -h 0.0.0.0 /api/swagger.yml
    ports:
      - 4010:4010
